language: node_js
node_js:
  - "5"
addons:
  mariadb: '15.1'
before_install: npm install -g mocha
install: npm install
before_script:
  - mysql -e "Create Database accounts DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;"
  - mysql --database=mysql -e "create user 'manager'@'localhost' identified by 'Password123';"
  - mysql --database=mysql -e "create user 'www'@'localhost' identified by 'Password123';"
  - mysql --database=mysql -u root -e "grant all privileges on *.* to 'manager'@'localhost';"
  - mysql --database=mysql -u root -e "grant select, insert, delete, execute, update on accounts.* to 'www'@'localhost';"
  - mysql -u root -e "flush privileges;"
  - bash ./database/install.sh
  - cat ./database/testData.sql | mysql --database=accounts -u manager -pPassword123;
  - npm start
  - until curl -s localhost:3000; do true; done > /dev/null
after_script:
  - npm stop
  - mysql -e "Drop Database accounts;"